{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Testcases.test_file_1.Test_001 object at 0x00000163D293A610>\n\n    def test_sum_001(self):\n        a=10\n        b=30\n        sum=a+b\n        print(sum)\n        if sum == 30:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nTestcases\\test_file_1.py:15: AssertionError"}, "attachments": [{"name": "stdout", "source": "1206112a-8ad6-4dfe-8fea-8ee41a186857-attachment.txt", "type": "text/plain"}], "start": 1691049578012, "stop": 1691049578013, "uuid": "572e6aab-f8a5-431f-960d-b8f4883f9682", "historyId": "7a9cd8b3660555471df7548d6ba79ff1", "testCaseId": "7a9cd8b3660555471df7548d6ba79ff1", "fullName": "Testcases.test_file_1.Test_001#test_sum_001", "labels": [{"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_file_1"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "Shelar"}, {"name": "thread", "value": "11872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_file_1"}]}